### ISSUE TITLE
Processing lists in lua filters [question]

### ISSUE THREAD

**Issue by retostauffer** [quarto-dev/quarto-shortcodes#2]
**Goal:** I am currently working on a shortcode for [bootstrap carousel](https://getbootstrap.com/docs/5.0/components/carousel/). To allow to define images, alt, and captions I try to configure it via `.yml` list.

My test `index.qmd` looks as follows:

```
---
title: "My Website"
carousel:
    - image: _images/unsplash-1.jpg
      alt: foooo
    - image: _images/unsplash-2.jpg
      alt: foooo
reto: "Just a test string"
---
```

My lua script (`carousel.lua`; shortcode extension) in a minimalized version looks as follows:

```
carousel = function(args, kwargs, meta)
    -- extracting Str from meta
    print(pandoc.utils.stringify(meta["reto"]))
    -- extracting List from meta
    print(pandoc.utils.stringify(meta["carousel"]))
    -- dummy return
    return pandoc.RawInline("html", "test")
end

return { ["carousel"] = carousel }
```

**The problem:** Processing `meta["reto"]` works as expected, however, `meta["carousel"]` (List) gives a `WARNING: Unsupported type 'List' for key carousel`.

**Question:** Is it somehow possible to process lists or a better way to access the meta needed, or is this just not possible with quarto/lua?

Any hint would be warmly welcome. Thanks in advance!
